name: Deploy Content to moshestestws [f2b80156-2c2d-4191-ae89-0f4dbad54c76]
# Note: This workflow will deploy everything in the root directory.
# To deploy content only from a specific path (for example SentinelContent):
#   1. Add the target path to the "paths" property like such
#    paths:
#    - 'SentinelContent/**'
#    - '!.github/workflows/**'
#    - '.github/workflows/sentinel-deploy-f2b80156-2c2d-4191-ae89-0f4dbad54c76.yml'
#   2. Append the path to the directory environment variable below
#       directory: '${{ github.workspace }}/SentinelContent'

on:
  push:
    branches: [ main ]
    paths:
    - '**'
    - '!.github/workflows/**'  # this filter prevents other workflow changes from triggering this workflow
    - '.github/workflows/sentinel-deploy-f2b80156-2c2d-4191-ae89-0f4dbad54c76.yml'

jobs:
  deploy-content:
    runs-on: windows-latest
    env:
      resourceGroupName: 'loganalyticstest'
      workspaceName: 'moshestestws'
      workspaceId: '57f2d9e0-5184-42ce-8620-50800390daaa'
      directory: '${{ github.workspace }}'
      cloudEnv: 'AzurePPE'
      contentTypes: 'AnalyticsRule'
      branch: 'main'
      sourceControlId: 'f2b80156-2c2d-4191-ae89-0f4dbad54c76'
      rootDirectory: '${{ github.workspace }}'
      githubAuthToken: ${{ secrets.GITHUB_TOKEN }}
      smartDeployment: 'true'
    permissions:
      contents: write
      id-token: write # Require write permission to Fetch an OIDC token.

    steps:
    - name: Login to Azure (Attempt 1)
      continue-on-error: true
      id: login1
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          Add-AzEnvironment `
          -Name AzurePPE `
          -ActiveDirectoryEndpoint https://login.windows-ppe.net `
          -ResourceManagerEndpoint https://management.azure.com/ `
          -ActiveDirectoryServiceEndpointResourceId https://management.core.windows.net `
          -GraphEndpoint https://graph.ppe.windows.net/ | out-null;
          $oidcTokenParams = @{
           Uri            = $env:ACTIONS_ID_TOKEN_REQUEST_URL
           Body           = @{
                 audience = 'api://AzureADTokenExchange'
           }
           Authentication = 'Bearer'
           Token          = $env:ACTIONS_ID_TOKEN_REQUEST_TOKEN | ConvertTo-SecureString -AsPlainText
          }
          $IdToken = (Invoke-RestMethod @oidcTokenParams).value
          Connect-AzAccount -ServicePrincipal -Tenant ${{ secrets.AZURE_SENTINEL_TENANTID_f2b801562c2d4191ae890f4dbad54c76 }} -Subscription ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_f2b801562c2d4191ae890f4dbad54c76 }} -ApplicationId ${{ secrets.AZURE_SENTINEL_CLIENTID_f2b801562c2d4191ae890f4dbad54c76 }} -Environment AzurePPE -FederatedToken $IdToken | out-null;

    - name: Wait 30 seconds if login attempt 1 failed
      if: ${{ steps.login1.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 2)
      continue-on-error: true
      id: login2
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          Add-AzEnvironment `
          -Name AzurePPE `
          -ActiveDirectoryEndpoint https://login.windows-ppe.net `
          -ResourceManagerEndpoint https://management.azure.com/ `
          -ActiveDirectoryServiceEndpointResourceId https://management.core.windows.net `
          -GraphEndpoint https://graph.ppe.windows.net/ | out-null;
          $oidcTokenParams = @{
           Uri            = $env:ACTIONS_ID_TOKEN_REQUEST_URL
           Body           = @{
                 audience = 'api://AzureADTokenExchange'
           }
           Authentication = 'Bearer'
           Token          = $env:ACTIONS_ID_TOKEN_REQUEST_TOKEN | ConvertTo-SecureString -AsPlainText
          }
          $IdToken = (Invoke-RestMethod @oidcTokenParams).value
          Connect-AzAccount -ServicePrincipal -Tenant ${{ secrets.AZURE_SENTINEL_TENANTID_f2b801562c2d4191ae890f4dbad54c76 }} -Subscription ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_f2b801562c2d4191ae890f4dbad54c76 }} -ApplicationId ${{ secrets.AZURE_SENTINEL_CLIENTID_f2b801562c2d4191ae890f4dbad54c76 }} -Environment AzurePPE -FederatedToken $IdToken | out-null;

    - name: Wait 30 seconds if login attempt 2 failed
      if: ${{ steps.login2.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 3)
      continue-on-error: false
      id: login3
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          Add-AzEnvironment `
          -Name AzurePPE `
          -ActiveDirectoryEndpoint https://login.windows-ppe.net `
          -ResourceManagerEndpoint https://management.azure.com/ `
          -ActiveDirectoryServiceEndpointResourceId https://management.core.windows.net `
          -GraphEndpoint https://graph.ppe.windows.net/ | out-null;
          $oidcTokenParams = @{
           Uri            = $env:ACTIONS_ID_TOKEN_REQUEST_URL
           Body           = @{
                 audience = 'api://AzureADTokenExchange'
           }
           Authentication = 'Bearer'
           Token          = $env:ACTIONS_ID_TOKEN_REQUEST_TOKEN | ConvertTo-SecureString -AsPlainText
          }
          $IdToken = (Invoke-RestMethod @oidcTokenParams).value
          Connect-AzAccount -ServicePrincipal -Tenant ${{ secrets.AZURE_SENTINEL_TENANTID_f2b801562c2d4191ae890f4dbad54c76 }} -Subscription ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_f2b801562c2d4191ae890f4dbad54c76 }} -ApplicationId ${{ secrets.AZURE_SENTINEL_CLIENTID_f2b801562c2d4191ae890f4dbad54c76 }} -Environment AzurePPE -FederatedToken $IdToken | out-null;

    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy Content to Microsoft Sentinel
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          ${{ github.workspace }}//.github/workflows/azure-sentinel-deploy-f2b80156-2c2d-4191-ae89-0f4dbad54c76.ps1